services:
  mosque-node:
    container_name: mosque-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mosque-strapi

  mosque-strapi:
    build:
      target: prod
    environment:
      NODE_ENV: production

  mosque-web:
    volumes:
      - ./nginx/mosque-prod.conf:/etc/nginx/conf.d/default.conf
