volumes:
  db_data:
  pma_data:

services:
  nginx:
    container_name: mosque-web-dev
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/mosque.conf:/etc/nginx/conf.d/default.conf
      - pma_data:/var/www/html/phpmyadmin:ro
    ports:
      - "80:80"

  db:
    container_name: mosque-db
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: mosque-pma
    image: phpmyadmin:fpm-alpine
    restart: always
    tty: true
    expose:
      - "9000"
    env_file:
      - .env
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mosque-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - pma_data:/var/www/html
