"""update menu

Revision ID: 24172d91c6fc
Revises: 728eed1d6304
Create Date: 2023-01-24 13:08:25.588351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24172d91c6fc'
down_revision = '728eed1d6304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'url')
    # ### end Alembic commands ###
