"""create page

Revision ID: f957074092cf
Revises: 24172d91c6fc
Create Date: 2023-01-24 14:59:21.295991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f957074092cf'
down_revision = '24172d91c6fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('is_menuitem', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_index(op.f('ix_page_url'), 'page', ['url'], unique=False)
    op.drop_index('ix_menu_id', table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_menu_id', 'menu', ['id'], unique=False)
    op.drop_index(op.f('ix_page_url'), table_name='page')
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
