default_context:
  project_name: 'fastapi-sample'
  project_slug: 'fastapi-sample'
  domain_main: 'fastapi-sample.com'
  domain_staging: 'stag.fastapi-sample.com'
  docker_swarm_stack_name_main: 'fastapi-sample-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-sample-com'
  secret_key: 'e516b250f2d3496dada4a8267ff8ae147021faab4530bc5e7a944c55664d6af2'
  first_superuser: 'admin@fastapi-sample.com'
  first_superuser_password: '1fcb74d4cc0a4e4f847150e0f9a2286472318f2909eafba44227a74a0a1f4dc0'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-sample.com", "https://stag.fastapi-sample.com", "https://fastapi-sample.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-sample.com'
  postgres_password: '6e6ba11ef089187ea2e8e20810b31c6501f963820ce84bead51fc9d91e7e2b79'
  pgadmin_default_user: 'admin@fastapi-sample.com'
  pgadmin_default_user_password: '1fcb74d4cc0a4e4f847150e0f9a2286472318f2909eafba44227a74a0a1f4dc0'
  traefik_constraint_tag: 'fastapi-sample.com'
  traefik_constraint_tag_staging: 'stag.fastapi-sample.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:1fcb74d4cc0a4e4f847150e0f9a2286472318f2909eafba44227a74a0a1f4dc0'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
