server {
  listen 80;
  listen [::]:80;
  server_name localhost;

  # main directory for app
  location / {
    proxy_pass http://gateway.docker.internal:5173/;
  }

  # subdirectory for api
  location /api/ {
    proxy_pass http://gateway.docker.internal:8000/api/;
  }
  location /docs/ {
    proxy_pass http://gateway.docker.internal:8000/docs/;
  }

  # subdirectory for phpmyadmin pages
  # location /pma {
  #   alias /var/www/html/phpmyadmin;
  #   index index.php index.html index.htm;
  # }

  # location ~ ^/pma/(.+\.php)$ {
  #   include fastcgi_params;
  #   fastcgi_split_path_info ^\/pma\/(.+\.php)(.*)$;
  #   fastcgi_pass mosque-pma:9000;
  #   fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
  # }

  # location @phpmyadmin {
  #   rewrite /phpmyadmin/(.*)$ /phpmyadmin/index.php?/$1 last;
  # }

  # subdirectory for register pages

  # location ^~ /register {

  #   alias /var/www/html/register;
  #   try_files $uri $uri/ @register;

  #   location ~ \.php$ {
  #     fastcgi_split_path_info ^\/register\/(.+\.php)(.*)$;
  #     fastcgi_pass php-fpm:9000;
  #     include fastcgi_params;
  #     fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
  #   }
  # }

  # location @register {
  #   rewrite /register/(.*)$ /register/index.php?/$1 last;
  # }

  # log_format debug_val_format "host[$host] http_origin[$http_origin]";
  # access_log /var/log/nginx/debug_val.log debug_val_format;
}
